### ISSUE TITLE
Training outcome problem

### ISSUE THREAD

**Issue by DC-SegNet** [dongbo811/AFFormer#13]
@dongbo811  Thank you for your work! I trained 150000epoch on the model based on cityscape data as required, but the final miou was only about 74.23, which is still a little short of the 78.7 mentioned in your paper. Here is my training log file, could you please help me check the problem? Thank you very much!
[20230802_150709.log](https://github.com/dongbo811/AFFormer/files/12256249/20230802_150709.log)

**Comment by dongbo811** [comment]
I quickly examined your question. 
From your training log (L244), it appears that the pre-trained weights and the defined model are mismatched.
