### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by zuo-ux** [dongbo811/AFFormer#2]
这个与AFFormer有关的代码不完整吧

**Comment by dongbo811** [comment]
Would you like to describe in detail?

**Comment by zuo-ux** [comment]
对的，想仔细看看里面的细节！

**Comment by dongbo811** [comment]
This repository is the completed. Can you describe your problem in detail?

**Comment by Haoru** [comment]
Parallel Heterogeneous Architecture的代码能否公开一下？

**Comment by dongbo811** [comment]
You can refer to ./tools/afformer.py

If you have more questions, please open this issue.

**Comment by Haoru** [comment]
冒昧问一下，论文中Clustering是哪一部分代码？

**Comment by dongbo811** [comment]
Considering that traditional clustering methods, such as Kmeans, requires multiple iterations, which greatly increases computational complexity, we adopt a simple local clustering strategy. Each local cluster center is initialized with its corresponding region by Equation 1, and the initialization weights can be further optimized during training. Considering the computational complexity and actual running speed, we currently rely on convolution to simplify the implementation of this strategy, which can also be implemented in other similar ways. The code can refer to afformer.py#L193.
