### ISSUE TITLE
KeyError: "EncoderDecoder: 'afformer_base is not in the models registry'"

### ISSUE THREAD

**Issue by SAWRJJ** [dongbo811/AFFormer#3]
Hello, thank you for the excellent paper, I also try to reproduce the model in the paper, but when I load the model it will appear KeyError: "EncoderDecoder: 'afformer_base is not in the models registry'". I hope you can answer my questions in your busy schedule

**Comment by liyaoshun** [comment]
modify */AFFormer/mmseg/models/backbones/__init__.py  &&  copy */AFFormer/tools/afformer.py  to */AFFormer/mmseg/models/backbones/afformer.py

from .resnet import ResNet
from .afformer import afformer_base
from .afformer import afformer_small
from .afformer import afformer_tiny

__all__ = [
    'ResNet',
    'afformer_base',
    'afformer_small',
    'afformer_tiny'
]

**Comment by liyaoshun** [comment]
> Hello, thank you for the excellent paper, I also try to reproduce the model in the paper, but when I load the model it will appear KeyError: "EncoderDecoder: 'afformer_base is not in the models registry'". I hope you can answer my questions in your busy schedule
modify */AFFormer/mmseg/models/backbones/init.py && copy */AFFormer/tools/afformer.py to */AFFormer/mmseg/models/backbones/afformer.py

from .resnet import ResNet
from .afformer import afformer_base
from .afformer import afformer_small
from .afformer import afformer_tiny

all = [
'ResNet',
'afformer_base',
'afformer_small',
'afformer_tiny'
]

**Comment by SAWRJJ** [comment]
> > Hello, thank you for the excellent paper, I also try to reproduce the model in the paper, but when I load the model it will appear KeyError: "EncoderDecoder: 'afformer_base is not in the models registry'". I hope you can answer my questions in your busy schedule
> > modify */AFFormer/mmseg/models/backbones/init.py && copy */AFFormer/tools/afformer.py to */AFFormer/mmseg/models/backbones/afformer.py
> 
> from .resnet import ResNet from .afformer import afformer_base from .afformer import afformer_small from .afformer import afformer_tiny
> 
> all = [ 'ResNet', 'afformer_base', 'afformer_small', 'afformer_tiny' ]

ty

**Comment by dongbo811** [comment]
Thank you for your attention!
