### ISSUE TITLE
分割模型的解码问题

### ISSUE THREAD

**Issue by 464hee** [dongbo811/AFFormer#7]
你好，CLS的decoder返回结果，还需要经过什么操作怎么才能转成语义分割中每一类的像素概率呢，我单独测试的模型返回结果有负数值，你能解答我的疑惑吗？谢谢
![image](https://user-images.githubusercontent.com/100740023/232040804-9f52ba68-6783-4e6a-9e66-a27aae2a7431.png)

**Comment by 464hee** [comment]
[AFFormer_net.zip](https://github.com/dongbo811/AFFormer/files/11232676/AFFormer_net.zip)
这是我问题复现的的示例代码，使用了 

from main.model.net.model_AFFormer import afformer_small
from main.model.net.decode_heads import CLS

**Comment by 464hee** [comment]
代码从github克隆的，默认参数从configs中获得

**Comment by dongbo811** [comment]
The output of cls needs to be transformed by softmax and argmax to get the final semantic category output.

**Comment by 464hee** [comment]
> The output of cls needs to be transformed by softmax and argmax to get the final semantic category output.

OK，I did the same thing
