### ISSUE TITLE
Number of GPUs used in the training process

### ISSUE THREAD

**Issue by martin-liao** [dongbo811/AFFormer#8]
Thanks for your fantastic work! 
I am curious that how many GPUs (maybe V100?) were used in the training (because I am trying to explore some downstream tasks based on your model.)
I have checked out the configuration folder and found that *samples_per_gpu* is set to 2 for Cityscapes and 4 for ADE20K. You said that the batch size is set to 16 and 8 for Cityscapes and ADE20K respectively, so you probably used 4 V100?

**Comment by dongbo811** [comment]
The number of GPUs used by ADE20k and Cityscapes is different, just ensure bacthsize=num_gpus * samples_per_gpu. Here you can set the relative size according to your own gpus.
