### ISSUE TITLE
AssertionError: MMCV==1.5.0 is used but incompatible. Please install mmcv>=2.0.0rc4.

### ISSUE THREAD

**Issue by Wslnjupt** [dongbo811/AFFormer#9]
![image](https://user-images.githubusercontent.com/109515479/236614420-548b5158-1374-474d-8fb5-242c3e4d1391.png)

**Comment by Wslnjupt** [comment]
为什么MMCV==1.5.0不能运行？

**Comment by dongbo811** [comment]
Sorry, I'm not sure either. If you still have problems following the installation, you can show your environment.

**Comment by InMyDreammer** [comment]
> 为什么MMCV==1.5.0不能运行？

请问您解决这个问题了吗？
